name: Code Scanner

on:
  push:
     branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main

jobs:
   code-scanner:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - uses: AppThreat/sast-scan-action@master
          name: Scan SAST Project
          with:
            type: "nodejs"
        
        - name: Setup CodeQL
          uses: github/codeql-action/init@v3
        - name: Autobuild CodeQL
          uses: github/codeql-action/autobuild@v3
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v3