name: Deploy to Heroku

on:
  push:
    branches:
      - heroku # Changing the branch here would also work
jobs:
  build:
    runs-on: ubuntu-latest
    environment: heroku
    steps:
        - uses: actions/checkout@v2
      
        - uses: akhileshns/heroku-deploy@v3.12.14 
          with:
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_app_name: ${{ vars.HEROKU_APP_NAME }}
            heroku_email: ${{ vars.HEROKU_EMAIL }}
            branch: "main"
          env:
            HD_DISCORD_TOKEN: ${{secrets.DISCORD_TOKEN}}
            HD_CLIENT_ID: ${{secrets.CLIENT_ID}}
            HD_DB_HOST: ${{secrets.DB_HOST}}
            HD_DB_USERNAME: ${{secrets.DB_USERNAME}}
            HD_DB_PASSWORD: ${{secrets.DB_PASSWORD}}