name: Deploy to On Premise Server

on:
  push:
    branches:
      - main # Changing the branch here would also work
    paths-ignore:
      - 'readme.md'
      - '.gitignore'
env:
  WORKDIR: /home/${{ secrets.SSH_USERNAME }}/muslimbot
  env: production

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to On Premise Server
    permissions:
        contents: 'read'
        id-token: 'write'
    defaults:
        run:
          shell: bash
    environment: on-premise
    steps:
        - uses: actions/checkout@v4
        
        - name: Set environments variable in a file .env
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              mkdir -p ${{ env.WORKDIR }}
              cd ${{ env.WORKDIR }}
              [ -e .env ] && rm .env
              echo "NODE_ENV=${{ env.env }}" >> .env
              echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
              echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> .env
              echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
              echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
              echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
              echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
              echo "HADITH_API_URL=${{ vars.HADITH_API_URL }}" >> .env
              echo "HADITH_SCHEDULE_HOUR=${{ vars.HADITH_SCHEDULE_HOUR }}" >> .env
              echo "HADITH_SCHEDULE_MINUTE=${{ vars.HADITH_SCHEDULE_MINUTE }}" >> .env
              echo "PRAYER_SCHEDULE_RULE=${{ vars.PRAYER_SCHEDULE_RULE }}" >> .env
        
        - name: Set output version
          id: vars
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
        - name: Check outputs
          run: echo ${{ steps.vars.outputs.sha_short }}

        - name: Login to Github Container Registry
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              echo "Login Github Container Registry..."
              sudo docker login ghcr.io -u samymokhtari -p ${{ secrets.READ_CR_PAT_MUSLIMBOT }}

        - name: 'Sync On Premise Server'
          uses: appleboy/ssh-action@v1.0.0
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              echo "Starting Docker Container..."
              cd ${{ env.WORKDIR }} 
              sudo docker stop muslimbot
              sudo docker rm muslimbot
              sudo docker run -d \
              --name muslimbot \
              --env-file .env \
              --restart=on-failure:3 \
              --mount type=bind,source=/var/log/muslimbot,target=/usr/src/bot/logs \
              --mount type=bind,source=/home/sm/quran,target=/usr/src/bot/quran \
              --restart=unless-stopped \
              ghcr.io/fivekage/muslimbot:${{ steps.vars.outputs.sha_short }}

              echo "Docker Container Started Successfully"
              echo "Remove .env file..."
              rm .env
              echo "Done"
